kk_blog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'  # 指定 app 命名空间

urlpatterns = [
    path('index/', views.index, name='index'),
    path('blog/detail/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('blog/pub', views.pub_blog, name='pub_blog'),
    path('blog/comment/pub', views.pub_comment, name='pub_comment'),
    path('search', views.search, name='search'),
]

kk_blog/kk_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),  # blog app
    path('auth/', include('kkauth.urls'))  # auth app
]

kk_blog/kkauth/urls.py
from django.urls import path
from . import views

app_name = 'kkauth'

urlpatterns = [
    path('login', views.kk_login, name='login'),
    path('logout', views.kk_logout, name='logout'),
    path('register', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='send_email_captcha'),
]

kk_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-kk博客</title>
    <!-- 引入 bootstrap.min.css -->
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <!-- 因为 bootstrap.min.js 依赖于 popper.min.js 所以先执行 popper.min.js包 -->
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <!-- 引入首页的样式文件 -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="pt-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>


            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <img src="{% static 'image/blog_pic.jpg' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                <li><a href="#" class="nav-link px-2 link-dark">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 link-dark">发布博客</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">笔记</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="GET">
                <input type="search" name="q" class="form-control input-group-lg" placeholder="搜索..." aria-label="搜索">
            </form>
            {% comment %}根据settings配置django.contrib.auth.context_processors.auth中获取到user{% endcomment %}
            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{% static 'image/blog_pic.jpg' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url 'kkauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                    <a href="{% url 'kkauth:login' %}" type="button"
                       class="btn btn-primary btn-outline-dark me-2">登录</a>
                    <a href="{% url 'kkauth:register' %}" type="button"
                       class="btn btn-light btn-outline-dark me-2">注册</a>
                </form>
            {% endif %}

        </div>
    </div>
</header>

{% comment %}
    这里的p-3代表内边距 m-3代表外边距
    p-3和m-3代表上下左右都有边距
    pt-内顶部的边距 pb-内底部的边距
    mt-外顶部的边距 mb-外底部的边距
    bg-white代表背景颜色是白色的
    rounded代表圆角
    {% endcomment %}
<main class="container bg-white p-4 rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

kk_blog/templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}博客详情{% endblock %}

{% block head %}
    {% comment %}引入代码高亮库{% endcomment %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static "image/blog_pic.jpg" %}" height="32" width="32" class="rounded-circle">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.publish_time | date:"Y年m月d日 h时i分" }}</span>发布
    </div>
    <hr>
    <div class="py-2">
        {% comment %}
        因为内容是来自富文本编辑器的
        所以用safe来保证html解析标签
        {% endcomment %}
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论（{{ blog.comments.all | length }}）：</h3>
        <form action="{% url 'blog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button class="btn btn-primary btn-outline-dark">评论</button>
            </div>
        </form>
    </div>
    <div>
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between text-bg-secondary">
                        <div class="user-info">
                            <img src="{% static 'image/blog_pic.jpg' %}" class="rounded-circle" width="40" height="40">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div class="create-time" style="">{{ comment.publish_time | date:"Y年m月d日 h时i分" }}</div>
                    </div>
                    <div class="mt-2">{{ comment.content }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>

    {% comment %}引入代码高亮库{% endcomment %}
    <script>
    hljs.highlightAll();
    </script>

{% endblock %}

kk_blog/templates/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block head %}{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    {% comment %}
            row-cols-2代表每一行展示两页
            row-gap-4代表每一行之间的间距
        {% endcomment %}
    <div class="row mt-4 row-cols-2 row-gap-4">
        {% for blog in blogs %}
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                    </div>
                    <div class="card-body" style="height: 120px">
                        {% comment %}striptags删掉所有html标签 truncatechars不能超过200个字符 {% endcomment %}
                        <p class="card-text">{{ blog.content | striptags | truncatechars:200 }}</p>
                    </div>
                    <div class="card-footer text-muted d-flex justify-content-between">
                        <div class="d-flex justify-content-between">
                            <img src="{% static 'image/blog_pic.jpg' %}" width="24" height="24"
                                 class="rounded-circle me-2">
                            <div>{{ blog.author.username }}</div>
                        </div>
                        类型：{{ blog.category }}
                        <div>发布时间：{{ blog.publish_time | date:"Y年m月d日 h时i分" }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

kk_blog/templates/login.html
{% extends 'base.html' %}

{% block title %}登录界面{% endblock %}
{% block head %}{% endblock %}
{% block main %}
    {% comment %}
    m-auto:水平居中
    {% endcomment %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>登录</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="请输入您的邮箱">
            </div>
            <div class="mb-3">
                <label class="form-label">密码</label>
                <input type="password" name="password" class="form-control" placeholder="请输入您的密码">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">记住我
                </label>
            </div>
            <div class="mt-3 d-grid">
                <button class="btn btn-primary">立即登录</button>
            </div>
            {% comment %}
               下面的也可以写成
               <div class="mt-3">
                   <button class="btn btn-primary w-100" type="button">立即登录</button>
               </div>
            {% endcomment %}

        </form>
    </div>
{% endblock %}

kk_blog/templates/pub_blog.html
{% extends 'base.html' %}

{% block title %}发布博客{% endblock %}
{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <!-- 引入wangeditor富文本编辑器的css文件、js文件、样式 -->
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <style>
        #editor-wrapper {
            border: 1px solid #ccc;
            z-index: 100;
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px
        }
    </style>
{% endblock %}
{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-2">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-2">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="select-category">
                    {% for val in categories %}
                        <option value="{{ val.id }}">{{ val.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-2">
                <label class="form-label">内容</label>
                {% comment %}
                    使用第三方wangEditor的富文本编辑器
                    {% endcomment %}
                <div id="editor-wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --> </div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-2 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

kk_blog/templates/register.html
{% extends 'base.html' %}
{% block title %}注册界面{% endblock %}
{% block head %}
    {% comment %}
    加载jquery.js文件和register.js文件
    {% endcomment %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>注册</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label class="form-label">邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label class="form-label">验证码</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="captcha" placeholder="验证码" aria-label="Recipient's username"
                           aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="mt-3">
                <button class="btn btn-primary w-100">立即注册</button>
            </div>
            {% comment %}
                下面的也可以写成
                <div class="mt-3">
                    <button class="btn btn-primary w-100" type="button">立即注册</button>
                </div>
            {% endcomment %}
        </form>
    </div>
{% endblock %}